version: 0.2

env:
  variables:
    JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport"

phases:
  install:
    runtime-versions:
      java: corretto8          # << 자바 8 강제
    commands:
      - echo "Install (deps warmup)"
      - mvn -q -B -DskipTests dependency:go-offline

  pre_build:
    commands:
      - echo "Pre-build (versions)"
      - java -version
      - mvn -v

  build:
    commands:
      - echo "Build & Test"
      - mvn -q -B package      # (테스트 포함; 필요시 -DskipTests)

  post_build:
    commands:
      - echo "Artifacts"
      - ls -al target || true

artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - /root/.m2/**
