version: "3.8"

services:
  redis-data:
    image: redis:7
    container_name: redis-data
    ports:
      - "6380:6379"
    volumes:
      - /app/portainer/volume/redis_volume/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    restart: always

    networks: # 서비스 블록(또는 공통 앵커) 안의 networks: 는 “이 컨테이너를 어느 네트워크에 연결할지”를 지>정
      - theyim-network #  - theyim-network 처럼, 연결할 네트워크 이름을 배열로 나열, 여러 개를 지정하면, 컨테이너가 그 네트워크들에 모두 동시에 연결

networks:
  theyim-network:    # Compose 스택이 사용할 네트워크를 선언
    external: true   # true 시 네트워크 자동 생성 방지하고 지정한 네트워크 사용