spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: theyim
    password: "0000"
    driver-class-name: oracle.jdbc.OracleDriver

  kafka:
    bootstrap-servers: localhost:29092 # 카프카 브로커 호스트:포트 (콤마로 여러 개 지정 가능)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: sse-group
      auto-offset-reset: earliest  # 컨슈머가 토픽 구독 시 오프셋이 없거나 찾을 수 없는 경우 읽는 위치 설정
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mybatis:
    # mapper XML 파일(들)을 모두 로드
    mapper-locations: classpath*:mapper/*.xml   # * 붙여 보세요
    # 도메인 객체 패키지 (type aliases)
    type-aliases-package: com.example.project.domain

  logging:
    level:
      org.mybatis: DEBUG
      org.mybatis.spring: DEBUG

